files:
  - source: /Translations/ru/**/*.csv
    translation: /Translations/%two_letters_code%/**/%original_file_name%
    first_line_contains_header: 1
    scheme: 'identifier,translation,source_phrase'
