name: "Godot: build and publish"

on:
  push:
    branches:
      - master

env:
  GAME: student-quest
  COMPANY: pixeltrain
  GODOT_VERSION: '3.3'
  RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
  RELEASE_KEYSTORE_USER: ${{ secrets.RELEASE_KEYSTORE_USER }}
  RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create directories
        run: mkdir -v -p build/windows build/linux build/mac build/android
      # Godot templates
      - name: Create directory for templates
        run: mkdir -v -p ~/.local/share/godot/templates
      - name: Move templates
        run: mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      # Godot config
      - name: Create directory for godot config
        run: mkdir -v -p ~/.config/godot
      - name: Copy godot config
        run: mv /root/.config/godot/editor_settings-3.tres ~/.config/godot/editor_settings-3.tres
      # Prepare keystore
      - name: Create keystore
        run: echo $RELEASE_KEYSTORE | base64 --decode > release.keystore
      - name: Set keystore path
        run: sed 's@keystore/release=".*"@keystore/release="release.keystore"@g' -i export_presets.cfg
      - name: Set keystore user
        run: sed 's@keystore/release_user=".*"@keystore/release_user="'$RELEASE_KEYSTORE_USER'"@g' -i export_presets.cfg
      - name: Set keystore password
        run: sed 's@keystore/release_password=".*"@keystore/release_password="'$RELEASE_KEYSTORE_PASSWORD'"@g' -i export_presets.cfg
      # Godot
      - name: Build for android
        run: godot -v --export "android" build/android/$GAME.apk
      - name: Build for windows
        run: godot -v --export "windows" build/windows/$GAME.exe
      - name: Build for linux
        run: godot -v --export "linux" build/linux/$GAME.x86_64
      - name: Build for mac
        run: godot -v --export "mac" build/mac/$GAME.zip
      # Butler
      # Do not forget to define BUTLER_API_KEY
      - name: Publish for windows
        run: butler push build/windows $COMPANY/$GAME:windows --userversion-file VERSION.txt
      - name: Publish for linux
        run: butler push build/linux $COMPANY/$GAME:linux --userversion-file VERSION.txt
      - name: Publish for mac
        run: butler push build/mac/$GAME.zip $COMPANY/$GAME:mac --userversion-file VERSION.txt
      - name: Publish for android
        run: butler push build/android/$GAME.apk $COMPANY/$GAME:android --userversion-file VERSION.txt
